
import { test, expect } from '@playwright/test';

test('Golden Path: https://stage.ianai.co/app', async ({ page }) => {
    // Generated by Curation Agent
    // Source: https://stage.ianai.co/app
    // Timestamp: 2026-01-09T02:30:00.000Z

    // Navigate
    await page.goto('https://stage.ianai.co/app');

    // Click Login with validation
    const loginBtn = page.locator('.button#login-btn').first();
    await loginBtn.waitFor({ state: 'visible', timeout: 10000 });
    if (await loginBtn.isEnabled()) {
        await loginBtn.click();
    } else {
        throw new Error('Login button is not enabled');
    }

    // Validation
    await expect(page).toHaveURL('https://stage.ianai.co/app');
    await expect(page).toHaveScreenshot('stage.ianai.co-app.png');
});
        